### ISSUE TITLE
tag names in JSON result

### ISSUE THREAD

**Issue by lithuaniantequila** [metatribal/xmlToJSON#18]
Hi everyone. 
My result for the test xml provided in Readme.md `<xml><a>It Works!</a></xml>` is `{"xml":[{"a":[{"_text":"It Works!"}]}]}`
Is there any option to remove the `_text` attribute that i'm not seeing? Has anyone encountered this before??
Thanks!

**Comment by julmot** [comment]
> that i'm not seeing?

What are you mean with that?

**Comment by lithuaniantequila** [comment]
> What are you mean with that?

> 

I'm asking if I don't know of an option to remove the tag name attribute? Basically, in the JSON example provided at the beginning of the threat I need to remove `"_text"` attribute

**Comment by julmot** [comment]
> I'm asking if I don't know of an option to remove the tag name attribute?

This sentence makes no sense for me, sorry.
If you want to delete an object key you can use `delete obj["_text"]`.

**Comment by lithuaniantequila** [comment]
> This sentence makes no sense for me, sorry.

> I understand what you mean now. Just to be clear I know nothing on JSON, its the first time I'm working with it, so excuse me if I dont use specific vocabulary.
I'll go back to the first bit of code I used. 
When I parse the XML: 
`<xml>
  <a>It Works!</a>
</xml>`
I get JSON (stringified)
`{
  "xml": [{
    "a": [{
      "_text": "It Works!"
    }]
  }]
}`
When I really need to get the JSON 
`{
  "xml": [{
    "a": "It Works!"
  }]
}`

**Comment by julmot** [comment]
Let's keep in your example: What would you do then if your `<a>` element has an attribute like `<a id="test">It works! <a>`? How would the JSON structure look then in your example?

**Comment by lithuaniantequila** [comment]
> What would you do then if your <a> element has an attribute like <a id="test">It works! <a>? How would the JSON structure look then in your example?

I think I see what you mean now, according to the documentation it should look something like 
`{
  "xml": [{
    "a": [{
      "_attr": {
        "id": {
          "_value": "test"
        }
      },
      "_text": "It works!"
    }]
  }]
}`
I won't provide XMLs with attributes in them, only with elements - in that case i think it would be possible to get the "_text" out and just get the desired "a": "It Works!" 

Im really sorry if im not getting through with the explanation, thanks for your help!

**Comment by julmot** [comment]
Ok, let's keep in your example: What would you do if your `<a>` element contains children? How would the JSON structure look then in your example?

**Comment by lithuaniantequila** [comment]
In the XML files I will be passing, the child elements won't contain any data, but the parent tag names would have to be represented in the JSON file.

**Comment by julmot** [comment]
If you have more than one value (the text) to display, e.g. because of childrens or attributes, you won't be able to have a structure like in your example. Most people have XML files that have at least one of them.
If you are confused about the name of the element ("_text") you can change this related to the documentation.

**Comment by lithuaniantequila** [comment]
Thanks for your help @julmot , clearly there is something I'm not getting right
I just don't understand why this XML:
`<xml>
  <1>
    <a>one</a>
  </1>
  <2>
    <b>two</b>
  </2>
</xml>`
can't be converted to a JSON like this  
`[{
  "xml": {
    "1":[
      {
      "a":"one"
      }
    ]
    "2":[
      {
        "b":"two"
      }
    ]
  }
}]`
I'll leave the issue open just  for a few hours to see if I get help from anyone else

**Comment by metatribal** [comment]
One of the design goals for this library was to provide a robust and **consistent** parsing of the xml.  That includes the ability to cope with nested children, attributes, namespaces, namespaced attributes, etc.  In order to accommodate all these different cases, I chose to use type identifiers (_text, _attr, _value, etc) for certain node types and to enforce their use for consistency.  You can change the values of these JSON keys using the options object as well as force objects instead of arrays (but you will lose explicit ordering).

If that doesn't work for you, you might look into x2js, https://github.com/abdmob/x2js, which provides some different parsing options.

**Comment by lithuaniantequila** [comment]
Thanks to @metatribal @julmot
